name: 'cache & depedencies'
description: this is for cacheing and install depedency of the file
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install depedency
      run: npm ci
      shell: bash