name: git_action_node
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download the code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: test the npm code
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      file-script: ${{ steps.publish.outputs.file-script }}
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install dependency
        run: npm ci
      - name: build website
        run: npm run build
      - name: upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: path
          path: dist
      - name: publish the job outputs
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'

  deployed:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: download the artifact
        uses: actions/download-artifact@v3
        with:
          name: path
      - name: view the download file
        run: ls
      - name: echo the command
        run: echo "deploying ...................."
      - name: view the output of the js file
        run: echo "${{ needs.build.outputs.script-file }}"
      
        
    